### ISSUE TITLE
请问svg绑定的event事件有说明文档吗？以及编辑界面的标题Mt-Edit能自己修改吗？

### ISSUE THREAD

**Issue by zmdcs** [yaolunmao/maotu-docs#12]
想实现在代码端就给开关绑定点击分合的动画，不用用户再去绑定了，可以实现吗？有说明文档就更好了，谢谢

**Comment by yaolunmao** [comment]
是需要创建配置文件的时候给图元默认动画效果吗？目前没有开放这个配置，需要的话我后面发布可以加上

**Comment by zmdcs** [comment]
哦，不用了，我突然想到开关的分合属性会直接根据收到的值变化的，一时间没想明白，我还想默认绑定点击就可以变化了，就是事件里自定义配置的那个效果





------------------ 原始邮件 ------------------
发件人: 咬轮猫 ***@***.***&gt;
发送时间: 2024年4月26日 13:11
收件人: yaolunmao/maotu-docs ***@***.***&gt;
抄送: zmdcs ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yaolunmao/maotu-docs] 请问svg绑定的event事件有说明文档吗？以及编辑界面的标题Mt-Edit能自己修改吗？ (Issue #12)





 
是需要创建配置文件的时候给图元默认动画效果吗？目前没有开放这个配置，需要的话我后面发布可以加上
