### ISSUE TITLE
MtEdit 自定义vue组件 setImportJson 可正常加载，MtPreview 加载自定义组件 setImportJson 报错，将props ={} 可显示

### ISSUE THREAD

**Issue by oliverdai** [yaolunmao/maotu-docs#14]
![err](https://github.com/yaolunmao/maotu-docs/assets/23209750/a4d8dac2-308f-4d87-82c3-5b6e773fd8b7)

**Comment by yaolunmao** [comment]
看样子是数据结构解析有问题了，maotu的版本号是多少，能否提供一个可以复现的例子

**Comment by oliverdai** [comment]
"maotu": "^0.3.5",
[demo.zip](https://github.com/user-attachments/files/15535625/demo.zip)

**Comment by oliverdai** [comment]
"maotu": "^0.3.5",
 首次加载可以，刷新页面从缓存取值后setImportJson 就会报错
[demo.zip](https://github.com/user-attachments/files/15535871/demo.zip)

**Comment by yaolunmao** [comment]
`MtEdit`组件和`MtPreview`组件是独立的，你的按钮组件只在编辑页使用`leftAsideStore.registerConfig`注册了，如果要在同一个项目里同时用`MtEdit`和`MtPreview`可以在`app.vue`或者`main.ts`中注册

**Comment by oliverdai** [comment]
好的，谢谢大佬，已验证

**Comment by 2000liu** [comment]
![Image](https://github.com/user-attachments/assets/c96227ec-53b7-4287-a513-175912b6c878)
这种情况我在测试自定义custom-svg时候，发现app已经全局注册过一次，所以在demo里面直接leftAsideStore.registerConfig注册了，但是拖拽就报错而且看不到图片，但是首页的app.vue是正常的
