### ISSUE TITLE
返回，保存，预览三个按钮点击无效

### ISSUE THREAD

**Issue by vic88chen** [yaolunmao/maotu-docs#16]
返回，保存，预览三个按钮点击无效

**Comment by vic88chen** [comment]
还有连线和文字的属性在预览模式下鼠标移到上面时怎样才能不显示

**Comment by yaolunmao** [comment]
参考https://github.com/yaolunmao/maotu-docs/tree/main/example/vue3
不显示只需要给预览组件showPopover设置为false即可
http://mt.yaolm.top/guide/attr-event/mt-preview.html
