### ISSUE TITLE
关于 组件 事件  建议

### ISSUE THREAD

**Issue by HANKAN1300** [yaolunmao/maotu-docs#17]
目前组件  事件 有四个  单击   双击   鼠标移入  鼠标移出，  是否可以增加输入框聚焦   失焦  事件，   在本文框输入中如果用鼠标移出触发，存在文本框还在输出 ，而鼠标移动到别的地方的可能性，造成文本框输入不能触发。

**Comment by yaolunmao** [comment]
不好意思我最近比较忙，有时间我会测试一下，如果可行的话会在下个版本加上

**Comment by HANKAN1300** [comment]
期待

**Comment by yaolunmao** [comment]
更新至0.3.6

**Comment by HANKAN1300** [comment]
好的 试下
