### ISSUE TITLE
ruoyi-vue-plus导入maotu失败

### ISSUE THREAD

**Issue by zmdcs** [yaolunmao/maotu-docs#18]
1.请问maotu能导入到vue2中吗？虽然我试了一下不行，会报错。
2.我在vue3中导入maotu，不论是mt-edit还是mt-preview都没办法使用的样子，其中mt-preview显示的是空白，mt-edit报错
![image](https://github.com/yaolunmao/maotu-docs/assets/40875421/b14c2209-f489-48e3-91f0-6d65effa240d)
请问您知道这个怎么解决吗？不论是导入示例项目的project.vue文件，还是教程中的代码都会报这个错

**Comment by yaolunmao** [comment]
vue2是没有办法直接用的，至于下面的报错能否给我提供一个可以复现的最小示例，这个错误信息很难判断出来问题出在哪里

**Comment by zmdcs** [comment]
谢谢您。我发现应该是版本问题造成的问题
