### ISSUE TITLE
注册两个组件，为什么  type: "vue",类型的可以执行MtPreview的onEventCallBack函数， type: "custom-svg"类型的不行

### ISSUE THREAD

**Issue by hutongwu** [yaolunmao/maotu-docs#19]
{
    id: "inputBox",
    title: "输入框",
    type: "vue",
    thumbnail: "/svgs/input.svg",
    width: 200,
    height: 30,
    props: {
      modelValue: {
        type: "input",
        val: "输入框",
        title: "文本",
      },
    },
    events: [
      {
        id: "22",
        type: "click",
        action: "customCode",
        change_attr: [],
        custom_code: "$mtEventCallBack($item_info)",
        trigger_rule: {
          value: null,
        },
      },
    ],
  },
  {
    id: "switch",
    title: "开关",
    type: "custom-svg",
    thumbnail: "/svgs/switch.svg",
    props: {
      state: {
        type: "switch",
        val: false,
        title: "开关",
      },
    },
    events: [
      {
        id: "23",
        type: "click",
        action: "customCode",
        change_attr: [],
        custom_code:
          "console.log('测试打印当前组件json',$item_info);\n$mtEventCallBack($item_info)",
        trigger_rule: {
          value: null,
        },
      },
    ],
  },
![cap](https://github.com/user-attachments/assets/0cc02e9b-f715-481f-984a-9987b870ac67)

**Comment by yaolunmao** [comment]
是bug，版本maotu@0.3.6-beta.4已修复
