### ISSUE TITLE
请问如何做图标开关切换

### ISSUE THREAD

**Issue by liu759045455** [yaolunmao/maotu-docs#2]
请问如何做图标开关切换，按照项目里的导入形式，拉到编辑器里面打不开 不知道为什么

**Comment by liu759045455** [comment]
![image](https://github.com/yaolunmao/maotu-docs/assets/73531913/8869097c-03e0-42c8-9d87-c56d9fc936b8)

**Comment by liu759045455** [comment]
![image](https://github.com/yaolunmao/maotu-docs/assets/73531913/f9adeecb-7513-40a8-81e9-829cd7e3fd46)

**Comment by yaolunmao** [comment]
图元开关切换您可以参考一下这里https://github.com/yaolunmao/maotu-ry/blob/main/ruoyi-ui-vue3/src/views/webtopo/components/circuit-breaker-b/index.vue

至于打不开的问题需要您这边提供更多的信息才能分析出来，是否有报错》或者提供一个可以复现的最小示例
