### ISSUE TITLE
按照ry示例，只要是自定义的组件或者SVG，编辑可以，但是无法预览

### ISSUE THREAD

**Issue by pjxu111** [yaolunmao/maotu-docs#29]
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'val')
    at maotu.js?v=1727395f:24242:16
    at Array.map (<anonymous>)
    at useExportJsonToDoneJson (maotu.js?v=1727395f:24237:20)
    at Proxy.setImportJson (maotu.js?v=1727395f:42507:79)
    at graph-view-page.vue:52:28

**Comment by pjxu111** [comment]
![微信截图_20240913231355](https://github.com/user-attachments/assets/91065f02-a997-4f1a-a917-d6a804cb67fa)

**Comment by pjxu111** [comment]
![Uploading 微信截图_20240913231355.png…]()

**Comment by pjxu111** [comment]
![微信截图_20240913231355](https://github.com/user-attachments/assets/969b2efc-d535-4181-9011-682a3c2a5c7d)

**Comment by pjxu111** [comment]
![微信截图_20240913231617](https://github.com/user-attachments/assets/033864ed-cff1-4d50-8fea-429b6a1309e2)
![微信截图_20240913231714](https://github.com/user-attachments/assets/d756737c-0d6b-464d-96cb-f1449a21de5b)

**Comment by pjxu111** [comment]
用自带的元素，或者图片文件都没有问题

**Comment by yaolunmao** [comment]
应该是预览组件没有用leftAsideStore.registerConfig注册图元，编辑页和预览页都需要单独注册，或者直接在main.ts或app.vue里面注册

**Comment by pjxu111** [comment]
我试一试，仔细看了例子，在例子里确实统一注册了

**Comment by pjxu111** [comment]
预览也可以了，感谢感谢
