### ISSUE TITLE
MtPreview页面显示的时候怎么做自适应全屏？

### ISSUE THREAD

**Issue by perfe110** [yaolunmao/maotu-docs#6]
给组件加css样式不管用 比如直接在行内设置 :style="{width:'100%' height:'100%'}"，MtPreview视图无法铺满页面空白处。

**Comment by yaolunmao** [comment]
目前`mt-preview`就是宽高100%的设置哈，检查一下是否您的其它样式影响了呢

**Comment by HANKAN1300** [comment]
应该和画布尺寸有关，浏览器尺寸大， 画布尺寸小就铺满不了，需要动态修改 尺寸

**Comment by perfe110** [comment]
> 目前`mt-preview`就是宽高100%的设置哈，检查一下是否您的其它样式影响了呢

感谢回复

**Comment by perfe110** [comment]
> 应该和画布尺寸有关，浏览器尺寸大， 画布尺寸小就铺满不了，需要动态修改 尺寸

这个方式我试过之后发现画布是动态修改的，感谢
