### ISSUE TITLE
运行的时候报错

### ISSUE THREAD

**Issue by 1486756632** [yaolunmao/maotu-docs#8]
oot@ubuntu:/usr/local/software/maotu/maotu# npm run serve

> maotu@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...

 ERROR  Failed to compile with 1 error                                                                                                                                                                           11:33:22 PM

 error  in ./src/App.vue?vue&type=template&id=7ba5bd90&ts=true

Module parse failed: Unexpected token (5:27)
File was processed with these loaders:
 * ./node_modules/vue-loader/dist/templateLoader.js
 * ./node_modules/vue-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
| const _hoisted_1 = { style: {"width":"100%","height":"100vh"} }
| 
> export function render(_ctx: any,_cache: any,$props: any,$setup: any,$data: any,$options: any) {
|   return (_openBlock(), _createElementBlock("div", _hoisted_1, [
|     _createVNode($setup["MtEdit"])

ERROR in ./src/App.vue?vue&type=template&id=7ba5bd90&ts=true (./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/App.vue?vue&type=template&id=7ba5bd90&ts=true) 5:27
Module parse failed: Unexpected token (5:27)
File was processed with these loaders:
 * ./node_modules/vue-loader/dist/templateLoader.js
 * ./node_modules/vue-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
| const _hoisted_1 = { style: {"width":"100%","height":"100vh"} }
| 
> export function render(_ctx: any,_cache: any,$props: any,$setup: any,$data: any,$options: any) {
|   return (_openBlock(), _createElementBlock("div", _hoisted_1, [
|     _createVNode($setup["MtEdit"])
 @ ./src/App.vue?vue&type=template&id=7ba5bd90&ts=true 1:0-196 1:0-196
 @ ./src/App.vue 1:0-72 6:68-74 16:71-18:3 17:29-35 16:2-18:4
 @ ./src/main.js 2:0-28 3:10-13

webpack compiled with 1 error

**Comment by yaolunmao** [comment]
参考https://github.com/yaolunmao/maotu-docs/tree/main/example/vue3
